services:
  greenx_db:
    image: mysql:8.0
    container_name: greenx-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ:-Asia/Karachi}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - greenx-db-volume:/var/lib/mysql
      - ./db/initdb:/docker-entrypoint-initdb.d:ro
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  influxdb_greenx:
    image: influxdb:2
    container_name: greenx-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME:-admin}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD:-admin123}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG:-greenx}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET:-actual_power}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN:-changeme}
      TZ: ${TZ:-Asia/Karachi}
    volumes:
      - influx-data:/var/lib/influxdb2

  greenx_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: greenx_backend:dev
    container_name: greenx-backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - greenx_db
      - influxdb_greenx
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # optional for live dev

  greenx_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: greenx_frontend:dev
    container_name: greenx-frontend
    restart: unless-stopped
    depends_on:
      - greenx_backend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"

volumes:
  greenx-db-volume:
  influx-data:


