version: "3.8"
services:
  architecture_db:
    image: mysql:latest
    restart: always
    container_name: DATABASE_Container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fca

  backend:
    container_name: Backend_Container
    restart: always
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

